import re
from typing import List

from copilot_engine.reports.schemas.report_schema import (
    ReportSchema,
    ReportSection,
)


class ResponseFormatter:
    """
    Professional Report Formatter.

    Responsibilities
    ----------------
    - Build report document
    - Clean AI-generated text
    - Normalize spacing
    - Skip empty sections
    - Produce consistent output
    """

    DIVIDER = "---"

    # ==========================================================
    # PUBLIC
    # ==========================================================

    @classmethod
    def format_report(cls, report: ReportSchema) -> str:
        """
        Convert ReportSchema into a clean report document.
        """

        parts: List[str] = []

        parts.append(cls._build_title(report))
        parts.append(cls._build_metadata(report))

        if report.summary:
            parts.append(cls._build_summary(report.summary))

        for section in report.sections:
            if cls._has_content(section):
                parts.append(cls._build_section(section))

        parts.append(cls._build_footer(report))

        document = "\n\n".join(
            part.strip()
            for part in parts
            if part.strip()
        )

        return cls._normalize(document)

    # ==========================================================
    # TITLE
    # ==========================================================

    @classmethod
    def _build_title(cls, report: ReportSchema) -> str:

        return f"# {report.title}"

    # ==========================================================
    # METADATA
    # ==========================================================

    @classmethod
    def _build_metadata(cls, report: ReportSchema) -> str:

        meta = report.metadata

        lines = [
            cls.DIVIDER,
            f"**Generated On:** {meta.generated_at}",
            f"**Generated By:** {meta.generated_by}",
            f"**Report Type:** {meta.report_type}",
        ]

        if meta.user_id:
            lines.append(f"**User ID:** {meta.user_id}")

        if meta.session_id:
            lines.append(f"**Session ID:** {meta.session_id}")

        if meta.trace_id:
            lines.append(f"**Trace ID:** {meta.trace_id}")

        lines.append(cls.DIVIDER)

        return "\n".join(lines)

    # ==========================================================
    # SUMMARY
    # ==========================================================

    @classmethod
    def _build_summary(cls, summary: str) -> str:

        summary = cls._clean(summary)

        return (
            "## Overall Summary\n\n"
            f"{summary}"
        )

    # ==========================================================
    # SECTION
    # ==========================================================

    @classmethod
    def _build_section(
        cls,
        section: ReportSection,
    ) -> str:

        content = cls._clean(section.content)

        return (
            f"## {section.title}\n\n"
            f"{content}"
        )

    # ==========================================================
    # FOOTER
    # ==========================================================

    @classmethod
    def _build_footer(
        cls,
        report: ReportSchema,
    ) -> str:

        footer = (
            report.footer
            or "This report was automatically generated by Coach Genie AI."
        )

        return (
            f"{cls.DIVIDER}\n"
            f"{footer}\n\n"
            f"*End of Report*"
        )

    # ==========================================================
    # CONTENT CHECK
    # ==========================================================

    @staticmethod
    def _has_content(section: ReportSection) -> bool:

        if section is None:
            return False

        if section.content is None:
            return False

        return bool(section.content.strip())

    # ==========================================================
    # CLEAN TEXT
    # ==========================================================

    @classmethod
    def _clean(cls, text: str) -> str:

        if not text:
            return ""

        text = text.replace("\r\n", "\n")
        text = text.replace("\r", "\n")

        text = text.strip()

        lines = []

        for line in text.split("\n"):
            lines.append(line.rstrip())

        text = "\n".join(lines)

        # Remove 3+ blank lines
        text = re.sub(
            r"\n{3,}",
            "\n\n",
            text,
        )

        return text

    # ==========================================================
    # FINAL NORMALIZATION
    # ==========================================================

    @classmethod
    def _normalize(cls, text: str) -> str:

        text = cls._clean(text)

        # Remove repeated dividers
        text = re.sub(
            rf"({re.escape(cls.DIVIDER)}\n)+",
            f"{cls.DIVIDER}\n",
            text,
        )

        # Ensure document ends with newline
        return text.rstrip() + "\n"

# copilot_engine/reports/formatters/response_formatter.py

# OLD CODE
# import textwrap
# from typing import List

# from copilot_engine.reports.schemas.report_schema import (
#     ReportSchema,
#     ReportSection,
# )


# class ResponseFormatter:

#     """
#     Production-grade report formatter.

#     Responsibilities:
#     - Normalize report content
#     - Beautify formatting
#     - Standardize spacing
#     - Prepare content for PDF/TXT rendering
#     """

#     # =====================================================
#     # PUBLIC FORMATTER
#     # =====================================================

#     @classmethod
#     def format_report(
#         cls,
#         report: ReportSchema,
#     ) -> str:

#         """
#         Convert structured report schema
#         into clean formatted text.
#         """

#         lines: List[str] = []

#         # =================================================
#         # HEADER
#         # =================================================

#         lines.extend(
#             cls._format_header(report)
#         )

#         # =================================================
#         # SUMMARY
#         # =================================================

#         if report.summary:

#             lines.extend(
#                 cls._format_summary(
#                     report.summary
#                 )
#             )

#         # =================================================
#         # SECTIONS
#         # =================================================

#         for section in report.sections:

#             lines.extend(
#                 cls._format_section(
#                     section
#                 )
#             )

#         # =================================================
#         # FOOTER
#         # =================================================

#         lines.extend(
#             cls._format_footer(report)
#         )

#         return "\n".join(lines)

#     # =====================================================
#     # HEADER FORMATTER
#     # =====================================================

#     @classmethod
#     def _format_header(
#         cls,
#         report: ReportSchema,
#     ) -> List[str]:

#         metadata = report.metadata

#         return [

#             "=" * 60,

#             cls._center_text(
#                 report.title.upper()
#             ),

#             "=" * 60,

#             "",

#             f"Generated At : "
#             f"{metadata.generated_at}",

#             f"Generated By : "
#             f"{metadata.generated_by}",

#             f"Report Type : "
#             f"{metadata.report_type}",

#             f"User ID      : "
#             f"{metadata.user_id or 'N/A'}",

#             f"Session ID   : "
#             f"{metadata.session_id or 'N/A'}",

#             f"Trace ID     : "
#             f"{metadata.trace_id or 'N/A'}",

#             "",
#         ]

#     # =====================================================
#     # SUMMARY FORMATTER
#     # =====================================================

#     @classmethod
#     def _format_summary(
#         cls,
#         summary: str,
#     ) -> List[str]:

#         return [

#             "=" * 60,

#             "SUMMARY",

#             "=" * 60,

#             "",

#             cls._clean_text(summary),

#             "",
#         ]

#     # =====================================================
#     # SECTION FORMATTER
#     # =====================================================

#     @classmethod
#     def _format_section(
#         cls,
#         section: ReportSection,
#     ) -> List[str]:

#         return [

#             "=" * 60,

#             section.title.upper(),

#             "=" * 60,

#             "",

#             cls._clean_text(
#                 section.content
#             ),

#             "",
#         ]

#     # =====================================================
#     # FOOTER FORMATTER
#     # =====================================================

#     @classmethod
#     def _format_footer(
#         cls,
#         report: ReportSchema,
#     ) -> List[str]:

#         footer = (
#             report.footer
#             or "Generated by Coach Genie AI"
#         )

#         return [

#             "",

#             "=" * 60,

#             footer,

#             "=" * 60,
#         ]

#     # =====================================================
#     # TEXT CLEANER
#     # =====================================================

#     @classmethod
#     def _clean_text(
#         cls,
#         text: str,
#     ) -> str:

#         """
#         Normalize LLM-generated text.
#         """

#         # Remove leading/trailing whitespace

#         text = text.strip()

#         # Normalize excessive newlines

#         while "\n\n\n" in text:

#             text = text.replace(
#                 "\n\n\n",
#                 "\n\n",
#             )

#         # Normalize spaces

#         lines = [

#             line.strip()

#             for line in text.splitlines()
#         ]

#         cleaned_text = "\n".join(lines)

#         # Wrap long lines for PDFs

#         wrapped_lines = []

#         for line in cleaned_text.splitlines():

#             wrapped_lines.extend(

#                 textwrap.wrap(
#                     line,
#                     width=100,
#                     replace_whitespace=False,
#                 )

#                 or [""]
#             )

#         return "\n".join(wrapped_lines)

#     # =====================================================
#     # CENTER TEXT
#     # =====================================================

#     @classmethod
#     def _center_text(
#         cls,
#         text: str,
#         width: int = 60,
#     ) -> str:

#         return text.center(width)
    
# # EXAMPLE OUTPUT

# # This produces:

# # ============================================================
# #                  STUDENT PERFORMANCE REPORT
# # ============================================================

# # Generated At : 2026-05-21 12:10:11
# # Generated By : Coach Genie AI
# # Report Type : performance_report
# # User ID      : student_102
# # Session ID   : sess_22
# # Trace ID     : trace_abc123

# # ============================================================
# # SUMMARY
# # ============================================================

# # The student demonstrates strong mathematical reasoning
# # abilities and consistent problem-solving skills.

# # ============================================================
# # STRENGTHS
# # ============================================================

# # - Algebra
# # - Geometry
# # - Analytical Thinking

# # ============================================================
# # AREAS TO IMPROVE
# # ============================================================

# # - Probability
# # - Time Management

# # ============================================================
# # Generated by Coach Genie AI
# # ============================================================