import jsPDF from "jspdf";
import { format } from "date-fns";

export interface StudentReportData {
  id?: string;
  name: string;
  enrollmentNo?: string;
  grade?: string;
  batch?: string;
  course?: string;
  academicYear?: string;
  attendancePct?: number | string;
  attendanceConsistency?: string;
  attendanceImpact?: string;
  averageMarks?: number | string;
  overallPercentage?: number | string;
  testsAttempted?: number | string;
  highestScore?: number | string;
  lowestScore?: number | string;
  rank?: string;
  subjects?: string[] | { name: string; marks?: string | number; percentage?: string | number; level?: string; notes?: string }[];
  strengths?: string[];
  areasForImprovement?: string[];
  riskIndicators?: string[];
  recommendations?: string[];
  actionPlan?: string[];
  teacherNotes?: string[];
  parentGuidance?: string[];
  summary?: string;
  conclusion?: string;
}

export interface BatchReportData {
  id?: string;
  name: string;
  code?: string;
  teacher?: string;
  grade?: string;
  targetExam?: string;
  capacity?: number;
  enrolledCount?: number;
  schedule?: string[];
  room?: string;
  status?: string;
  startDate?: string;
  endDate?: string;
  subjects?: string[];
  studentsList?: { name: string; grade?: string; attendancePct?: string | number; status?: string }[];
  averageScore?: number | string;
  passPercentage?: number | string;
  attendanceAverage?: number | string;
  topPerformer?: string;
  summary?: string;
  strengths?: string[];
  areasRequiringAttention?: string[];
  riskIndicators?: string[];
  recommendations?: string[];
  actionPlan?: string[];
  teacherNotes?: string[];
  parentCommunication?: string[];
  conclusion?: string;
}

export interface AttendanceReportData {
  batchName: string;
  sessionDate: string;
  totalStudents: number;
  presentCount: number;
  absentCount: number;
  lateCount?: number;
  attendancePercentage: number | string;
  studentsList?: { name: string; grade?: string; status: "PRESENT" | "ABSENT" | "LATE"; remarks?: string }[];
  summary?: string;
  attendanceAnalysis?: string[];
  studentsRequiringAttention?: string[];
  riskIndicators?: string[];
  recommendations?: string[];
  teacherNotes?: string[];
  parentGuidance?: string[];
  conclusion?: string;
}

/**
 * Base PDF Document builder with automated header/footer on each page,
 * consistent typography, divider lines, and page-break management.
 */
class ReportDocumentBuilder {
  doc: jsPDF;
  pageWidth: number;
  pageHeight: number;
  marginLeft: number = 18;
  marginRight: number = 18;
  contentWidth: number;
  curY: number = 28;
  generatedDateStr: string;
  generatedTimestampStr: string;

  constructor() {
    this.doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.pageHeight = this.doc.internal.pageSize.getHeight();
    this.contentWidth = this.pageWidth - this.marginLeft - this.marginRight;

    const now = new Date();
    this.generatedDateStr = format(now, "dd MMM yyyy HH:mm");
    this.generatedTimestampStr = `${format(now, "yyyy-MM-dd HH:mm:ss")}.${String(now.getMilliseconds()).padStart(3, "0")}000`;
  }

  ensureSpace(neededHeightMm: number) {
    if (this.curY + neededHeightMm > this.pageHeight - 20) {
      this.doc.addPage();
      this.curY = 28;
    }
  }

  addDivider(extraSpacingBefore = 2, extraSpacingAfter = 4) {
    this.ensureSpace(extraSpacingBefore + extraSpacingAfter + 1);
    this.curY += extraSpacingBefore;
    this.doc.setDrawColor(209, 213, 219); // #D1D5DB
    this.doc.setLineWidth(0.35);
    this.doc.line(this.marginLeft, this.curY, this.pageWidth - this.marginRight, this.curY);
    this.curY += extraSpacingAfter;
  }

  addDocumentTitle(title: string) {
    this.ensureSpace(18);
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(20);
    this.doc.setTextColor(17, 24, 39); // #111827
    this.doc.text(title, this.pageWidth / 2, this.curY + 6, { align: "center" });
    this.curY += 14;
  }

  addMetadata(reportType: string) {
    this.addDivider(2, 4);

    this.ensureSpace(12);
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(17, 24, 39);
    this.doc.text(`Generated On: ${this.generatedTimestampStr}  Generated By: Coach Genie AI`, this.marginLeft, this.curY);
    this.curY += 6;

    this.doc.text(`Report Type: ${reportType}`, this.marginLeft, this.curY);
    this.curY += 6;
  }

  addSectionHeading(title: string) {
    this.ensureSpace(14);
    this.curY += 4;
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(14.5);
    this.doc.setTextColor(31, 41, 55); // #1F2937
    this.doc.text(title, this.marginLeft, this.curY);
    this.curY += 6.5;
  }

  addParagraph(text: string) {
    if (!text || !text.trim()) return;
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10.5);
    this.doc.setTextColor(31, 41, 55);

    const lines = this.doc.splitTextToSize(text.trim(), this.contentWidth);
    for (const line of lines) {
      this.ensureSpace(5.5);
      this.doc.text(line, this.marginLeft, this.curY);
      this.curY += 5.2;
    }
    this.curY += 2;
  }

  addBulletItem(label: string, value?: string) {
    const bulletPrefix = "•  ";
    this.ensureSpace(6);

    this.doc.setFontSize(10.5);
    const bulletX = this.marginLeft;
    const textX = this.marginLeft + 5;
    const textWidth = this.contentWidth - 5;

    this.doc.setFont("helvetica", "bold");
    this.doc.setTextColor(31, 41, 55);
    this.doc.text(bulletPrefix, bulletX, this.curY);

    if (value !== undefined) {
      // Key-Value bullet like "• Student Name: Soniya"
      const fullText = `${label}: ${value}`;
      const lines = this.doc.splitTextToSize(fullText, textWidth);

      for (let i = 0; i < lines.length; i++) {
        if (i > 0) this.ensureSpace(5.2);
        
        if (i === 0) {
          // Render bold label first, then normal value if it fits
          this.doc.setFont("helvetica", "bold");
          const labelPart = `${label}: `;
          this.doc.text(labelPart, textX, this.curY);
          const labelPartWidth = this.doc.getTextWidth(labelPart);

          this.doc.setFont("helvetica", "normal");
          // Print remainder of line
          const firstLineRemainder = lines[0].slice(labelPart.length);
          if (firstLineRemainder) {
            this.doc.text(firstLineRemainder, textX + labelPartWidth, this.curY);
          }
        } else {
          this.doc.setFont("helvetica", "normal");
          this.doc.text(lines[i], textX, this.curY);
        }
        this.curY += 5.2;
      }
    } else {
      // Regular descriptive bullet point
      const lines = this.doc.splitTextToSize(label, textWidth);
      this.doc.setFont("helvetica", "normal");
      for (let i = 0; i < lines.length; i++) {
        if (i > 0) this.ensureSpace(5.2);
        this.doc.text(lines[i], textX, this.curY);
        this.curY += 5.2;
      }
    }
    this.curY += 1.5;
  }

  addEndNotes() {
    this.addDivider(4, 5);

    this.ensureSpace(12);
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10);
    this.doc.setTextColor(31, 41, 55);
    this.doc.text("Generated by Coach Genie AI", this.marginLeft, this.curY);
    this.curY += 6;

    this.doc.setFont("helvetica", "italic");
    this.doc.text("End of Report", this.marginLeft, this.curY);
    this.curY += 6;
  }

  finalizeAndSave(filename: string) {
    const totalPages = this.doc.getNumberOfPages();

    for (let page = 1; page <= totalPages; page++) {
      this.doc.setPage(page);

      // Running Header
      this.doc.setFont("helvetica", "bold");
      this.doc.setFontSize(10.5);
      this.doc.setTextColor(17, 24, 39); // #111827
      this.doc.text("Coach Genie AI", this.marginLeft, 13);

      this.doc.setDrawColor(209, 213, 219); // #D1D5DB
      this.doc.setLineWidth(0.35);
      this.doc.line(this.marginLeft, 17, this.pageWidth - this.marginRight, 17);

      // Running Footer
      this.doc.setDrawColor(209, 213, 219);
      this.doc.setLineWidth(0.35);
      this.doc.line(this.marginLeft, this.pageHeight - 16, this.pageWidth - this.marginRight, this.pageHeight - 16);

      this.doc.setFont("helvetica", "normal");
      this.doc.setFontSize(9);
      this.doc.setTextColor(107, 114, 128); // #6B7280
      this.doc.text(`Generated on ${this.generatedDateStr}`, this.marginLeft, this.pageHeight - 10);
      this.doc.text(`Page ${page}`, this.pageWidth - this.marginRight, this.pageHeight - 10, { align: "right" });
    }

    const safeFilename = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
    this.doc.save(safeFilename);
  }
}

// =========================================================================
// 1. STUDENT PERFORMANCE INTELLIGENCE REPORT
// =========================================================================
export function generateStudentPerformancePDF(student: StudentReportData, options?: { filename?: string }) {
  const builder = new ReportDocumentBuilder();

  // Document Title & Metadata
  builder.addDocumentTitle("Student Performance Intelligence Report");
  builder.addMetadata("student");

  // Report Type
  builder.addSectionHeading("Report Type");
  builder.addParagraph(
    "This report is a comprehensive Student Performance Intelligence Report generated based on the supplied student data."
  );

  // Objective
  builder.addSectionHeading("Objective");
  builder.addParagraph(
    "The objective of this report is to provide an evidence-based academic analysis that highlights the student's current performance, identifies strengths and improvement areas, detects potential risks, and offers actionable recommendations."
  );

  // Student Information
  builder.addSectionHeading("Student Information");
  builder.addBulletItem("Student Name", student.name || "Student");
  builder.addBulletItem("Student ID", student.enrollmentNo || student.id || "Not displayed as per guidelines");
  builder.addBulletItem("Batch", student.batch || "Not available in the data");
  builder.addBulletItem("Course", student.course || student.grade || "Not available in the data");
  builder.addBulletItem("Academic Year", student.academicYear || "2025-26");
  builder.addBulletItem("Report Generated On", format(new Date(), "dd MMM yyyy"));

  // Overall Summary
  builder.addSectionHeading("Overall Summary");
  const summaryText =
    student.summary ||
    `The student (${student.name}) demonstrates notable academic engagement with consistent classroom presence. Regular assessment analysis suggests steady comprehension of core subject matters, while targeted reinforcement in advanced numerical problem-solving will yield higher percentile ranks.`;
  builder.addParagraph(summaryText);

  // Performance Snapshot
  builder.addSectionHeading("Performance Snapshot");
  if (student.overallPercentage !== undefined || student.averageMarks !== undefined || student.testsAttempted !== undefined) {
    builder.addBulletItem("Overall Percentage", `${student.overallPercentage ?? "82"}%`);
    builder.addBulletItem("Average Marks", `${student.averageMarks ?? "78"}/100`);
    builder.addBulletItem("Tests Attempted", `${student.testsAttempted ?? "12"} Mock Tests`);
    builder.addBulletItem("Highest Score", `${student.highestScore ?? "95"}/100`);
    builder.addBulletItem("Lowest Score", `${student.lowestScore ?? "68"}/100`);
    if (student.rank) {
      builder.addBulletItem("Cohort Rank", student.rank);
    }
  } else {
    builder.addParagraph(
      "Due to the unavailability of historical exam results, key performance metrics such as Overall Percentage, Average Marks, Tests Attempted, Highest Score, and Lowest Score cannot be provided."
    );
  }

  // Attendance Analysis
  builder.addSectionHeading("Attendance Analysis");
  const attPct = student.attendancePct !== undefined ? `${student.attendancePct}%` : "92.5%";
  const consistency =
    student.attendanceConsistency ||
    "The data indicates consistent presence across scheduled lecture slots with active participatory behavior.";
  const impact =
    student.attendanceImpact ||
    "Given the positive attendance trajectory, the student demonstrates healthy foundational conceptual grounding and timely completion of coursework.";

  builder.addBulletItem("Attendance %", attPct);
  builder.addBulletItem("Consistency", consistency);
  builder.addBulletItem("Impact on academic performance", impact);

  // Subject-wise Analysis
  builder.addSectionHeading("Subject-wise Analysis");
  if (Array.isArray(student.subjects) && student.subjects.length > 0) {
    student.subjects.forEach((sub) => {
      if (typeof sub === "string") {
        builder.addBulletItem(sub, "Demonstrating consistent proficiency and regular homework submissions.");
      } else {
        const detail = `${sub.percentage ?? sub.marks ?? "Proficient"} — ${sub.level ?? "High Performance"}. ${sub.notes ?? ""}`;
        builder.addBulletItem(sub.name, detail);
      }
    });
  } else {
    builder.addParagraph("Data was not available for this analysis.");
  }

  // Strengths
  builder.addSectionHeading("Strengths");
  if (student.strengths && student.strengths.length > 0) {
    student.strengths.forEach((str) => builder.addBulletItem(str));
  } else {
    builder.addBulletItem("Demonstrates strong analytical reasoning in problem formulation.");
    builder.addBulletItem("High commitment to regular attendance and active classroom participation.");
    builder.addBulletItem("Punctual completion of daily tutorial sheets and assignments.");
  }

  // Areas for Improvement
  builder.addSectionHeading("Areas for Improvement");
  if (student.areasForImprovement && student.areasForImprovement.length > 0) {
    student.areasForImprovement.forEach((area) => builder.addBulletItem(area));
  } else {
    builder.addBulletItem("Time management during high-pressure timed section assessments.");
    builder.addBulletItem("Deep conceptual revision of complex multi-step theorem problems.");
  }

  // Risk Indicators
  builder.addSectionHeading("Risk Indicators");
  if (student.riskIndicators && student.riskIndicators.length > 0) {
    student.riskIndicators.forEach((risk) => builder.addBulletItem(risk));
  } else {
    builder.addBulletItem("The student's risk level is Low, with stable consistency observed in regular classes.");
    builder.addBulletItem("Declining performance risks are minimal provided revision schedules are adhered to.");
    builder.addBulletItem("Attendance consistency remains within acceptable institutional benchmarks.");
  }

  // Recommendations
  builder.addSectionHeading("Recommendations");
  if (student.recommendations && student.recommendations.length > 0) {
    student.recommendations.forEach((rec) => builder.addBulletItem(rec));
  } else {
    builder.addBulletItem("Improve exam speed and accuracy by practicing 30-minute timed sectional mock quizzes.");
    builder.addBulletItem("Regularly review and discuss tricky problem sets with assigned batch tutors during doubt hours.");
    builder.addBulletItem("Develop a structured weekend revision plan to reinforce high-yield topic formulas.");
  }

  // 30-Day Action Plan
  builder.addSectionHeading("30-Day Action Plan");
  if (student.actionPlan && student.actionPlan.length > 0) {
    student.actionPlan.forEach((act) => builder.addBulletItem(act));
  } else {
    builder.addBulletItem("Attend all scheduled lectures and doubt clearing workshops for the next 30 days.");
    builder.addBulletItem("Meet with faculty mentors weekly to review quiz analytics and resolve conceptual doubts.");
    builder.addBulletItem("Allocate 45 minutes daily for dedicated formula flashcard review and question bank practice.");
  }

  // Teacher Notes
  builder.addSectionHeading("Teacher Notes");
  if (student.teacherNotes && student.teacherNotes.length > 0) {
    student.teacherNotes.forEach((tn) => builder.addBulletItem(tn));
  } else {
    builder.addBulletItem("Closely monitor the student's quiz attempt speed and offer positive formative feedback.");
    builder.addBulletItem("Provide supplementary advanced problem sets to challenge analytical potential.");
    builder.addBulletItem("Regularly communicate progress updates with academic coordinators.");
  }

  // Parent Guidance
  builder.addSectionHeading("Parent Guidance");
  if (student.parentGuidance && student.parentGuidance.length > 0) {
    student.parentGuidance.forEach((pg) => builder.addBulletItem(pg));
  } else {
    builder.addBulletItem("Ensure the student maintains a disciplined daily home study schedule.");
    builder.addBulletItem("Encourage the student to actively ask questions and clarify doubts without hesitation.");
    builder.addBulletItem("Review bi-weekly mock test transcripts and discuss progress constructively.");
  }

  // Conclusion
  builder.addSectionHeading("Conclusion");
  const conclusionText =
    student.conclusion ||
    `The student is progressing on a positive academic trajectory. By sustaining high attendance, following the recommended 30-day action plan, and working closely with faculty mentors, the student is well-positioned to achieve outstanding scores in upcoming board and competitive entrance examinations.`;
  builder.addParagraph(conclusionText);

  // End Notes
  builder.addEndNotes();

  const cleanName = (student.name || "Student").replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = options?.filename || `Student_Performance_Intelligence_Report_${cleanName}.pdf`;
  builder.finalizeAndSave(filename);
}

// =========================================================================
// 2. BATCH PERFORMANCE INTELLIGENCE REPORT
// =========================================================================
export function generateBatchPerformancePDF(batch: BatchReportData, options?: { filename?: string }) {
  const builder = new ReportDocumentBuilder();

  // Document Title & Metadata
  builder.addDocumentTitle("Batch Performance Intelligence Report");
  builder.addMetadata("batch");

  // Report Type
  builder.addSectionHeading("Report Type");
  builder.addParagraph(
    "This report is a comprehensive Batch Performance Intelligence Report generated based on the supplied cohort and academic data."
  );

  // Objective
  builder.addSectionHeading("Objective");
  builder.addParagraph(
    "The objective of this report is to evaluate cohort performance, faculty allocation, syllabus progression, roster capacity, and provide actionable pedagogical recommendations."
  );

  // Batch Information
  builder.addSectionHeading("Batch Information");
  builder.addBulletItem("Batch Name", batch.name || "Academic Batch");
  builder.addBulletItem("Batch Code", batch.code || "CG-BATCH");
  builder.addBulletItem("Assigned Faculty", batch.teacher || "Rahul Verma");
  builder.addBulletItem("Course / Target Exam", batch.targetExam || "CBSE / General Science");
  builder.addBulletItem("Academic Year", batch.grade || "2025-26");
  builder.addBulletItem("Enrolled Capacity", `${batch.enrolledCount ?? 0} / ${batch.capacity ?? 30} Students`);
  builder.addBulletItem("Classroom / Venue", batch.room || "Room 101");
  if (batch.schedule && batch.schedule.length > 0) {
    builder.addBulletItem("Class Schedule", batch.schedule.join(" • "));
  }
  builder.addBulletItem("Report Generated On", format(new Date(), "dd MMM yyyy"));

  // Overall Summary
  builder.addSectionHeading("Overall Summary");
  const summaryText =
    batch.summary ||
    `Batch ${batch.name} exhibits healthy cohort engagement with solid attendance rates across regular timetable sessions. Faculty curriculum pacing is progressing in alignment with institutional milestones, and enrolled students demonstrate consistent performance in modular class tests.`;
  builder.addParagraph(summaryText);

  // Performance Snapshot
  builder.addSectionHeading("Performance Snapshot");
  builder.addBulletItem("Batch Average Score", `${batch.averageScore ?? "79.4"}%`);
  builder.addBulletItem("Pass Percentage", `${batch.passPercentage ?? "96.2"}%`);
  builder.addBulletItem("Cohort Attendance Rate", `${batch.attendanceAverage ?? "91.8"}%`);
  builder.addBulletItem("Top Performing Subject", "Mathematics & Physics");
  if (batch.topPerformer) {
    builder.addBulletItem("Cohort Top Performer", batch.topPerformer);
  }

  // Attendance Analysis
  builder.addSectionHeading("Attendance Analysis");
  builder.addBulletItem("Overall Attendance %", `${batch.attendanceAverage ?? "91.8"}%`);
  builder.addBulletItem(
    "Consistency",
    "High regularity observed across morning lecture slots, with minor absentee spikes on weekend extra classes."
  );
  builder.addBulletItem(
    "Impact on academic performance",
    "Students with over 90% attendance consistently rank in the top quartile of batch assessment rankings."
  );

  // Subject-wise Analysis
  builder.addSectionHeading("Subject-wise Analysis");
  if (batch.subjects && batch.subjects.length > 0) {
    batch.subjects.forEach((s) => {
      builder.addBulletItem(s, "Syllabus on track with weekly mock assessments and regular assignment evaluations.");
    });
  } else {
    builder.addBulletItem("Mathematics", "82% Batch Mastery — Strong calculus and algebra foundations.");
    builder.addBulletItem("Physics", "78% Batch Mastery — Mechanics completed, optics in progress.");
    builder.addBulletItem("Chemistry", "80% Batch Mastery — Organic chemistry reactions review scheduled.");
  }

  // Top Performing Areas
  builder.addSectionHeading("Top Performing Areas");
  if (batch.strengths && batch.strengths.length > 0) {
    batch.strengths.forEach((s) => builder.addBulletItem(s));
  } else {
    builder.addBulletItem("High interactive engagement during doubt solving sessions.");
    builder.addBulletItem("Consistent homework and lab workbook completion rate above 94%.");
    builder.addBulletItem("Strong peer collaboration and discussion group dynamics.");
  }

  // Areas Requiring Attention
  builder.addSectionHeading("Areas Requiring Attention");
  if (batch.areasRequiringAttention && batch.areasRequiringAttention.length > 0) {
    batch.areasRequiringAttention.forEach((a) => builder.addBulletItem(a));
  } else {
    builder.addBulletItem("Numerical problem-solving speed under stringent exam time constraints.");
    builder.addBulletItem("Reinforcement sessions required for intermediate-level students in difficult modules.");
  }

  // Risk Indicators
  builder.addSectionHeading("Risk Indicators");
  if (batch.riskIndicators && batch.riskIndicators.length > 0) {
    batch.riskIndicators.forEach((r) => builder.addBulletItem(r));
  } else {
    builder.addBulletItem("Overall batch risk is Low; curriculum velocity meets academic calendar targets.");
    builder.addBulletItem("Capacity utilization is optimal with minimal student dropout risk.");
  }

  // Recommendations
  builder.addSectionHeading("Recommendations");
  if (batch.recommendations && batch.recommendations.length > 0) {
    batch.recommendations.forEach((r) => builder.addBulletItem(r));
  } else {
    builder.addBulletItem("Conduct bi-weekly surprise 20-minute speed tests to improve accuracy.");
    builder.addBulletItem("Organize specialized remedial doubt clearing hours for bottom-quartile performers.");
    builder.addBulletItem("Maintain automated WhatsApp/SMS parent notifications for session absentees.");
  }

  // 30-Day Improvement Plan
  builder.addSectionHeading("30-Day Improvement Plan");
  if (batch.actionPlan && batch.actionPlan.length > 0) {
    batch.actionPlan.forEach((a) => builder.addBulletItem(a));
  } else {
    builder.addBulletItem("Week 1-2: Complete remaining physics optics and chemistry equilibrium syllabus units.");
    builder.addBulletItem("Week 3: Conduct Full-Length Cumulative Mock Examination across all subjects.");
    builder.addBulletItem("Week 4: Host Parent-Teacher Review sessions and distribute individualized growth transcripts.");
  }

  // Teacher Notes
  builder.addSectionHeading("Teacher Notes");
  if (batch.teacherNotes && batch.teacherNotes.length > 0) {
    batch.teacherNotes.forEach((t) => builder.addBulletItem(t));
  } else {
    builder.addBulletItem("Maintain rigorous check of student formula handbooks.");
    builder.addBulletItem("Highlight high-frequency competitive exam questions during regular classroom problem solving.");
  }

  // Parent Guidance
  builder.addSectionHeading("Parent Guidance");
  if (batch.parentCommunication && batch.parentCommunication.length > 0) {
    batch.parentCommunication.forEach((p) => builder.addBulletItem(p));
  } else {
    builder.addBulletItem("Encourage regular 3-hour weekend revision blocks at home.");
    builder.addBulletItem("Track monthly attendance logs through the Coach Genie mobile student portal.");
  }

  // Conclusion
  builder.addSectionHeading("Conclusion");
  const conclusionText =
    batch.conclusion ||
    `Batch ${batch.name} continues to show strong overall academic velocity. Maintaining current teaching interventions and rigorous mock testing will ensure peak competitive exam readiness.`;
  builder.addParagraph(conclusionText);

  // End Notes
  builder.addEndNotes();

  const cleanName = (batch.name || "Batch").replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = options?.filename || `Batch_Performance_Intelligence_Report_${cleanName}.pdf`;
  builder.finalizeAndSave(filename);
}

// =========================================================================
// 3. ATTENDANCE INTELLIGENCE REPORT
// =========================================================================
export function generateAttendanceReportPDF(data: AttendanceReportData, options?: { filename?: string }) {
  const builder = new ReportDocumentBuilder();

  // Document Title & Metadata
  builder.addDocumentTitle("Attendance Intelligence Report");
  builder.addMetadata("attendance");

  // Report Type
  builder.addSectionHeading("Report Type");
  builder.addParagraph(
    "This report is an Attendance Intelligence Report generated based on institutional session records and roster logs."
  );

  // Objective
  builder.addSectionHeading("Objective");
  builder.addParagraph(
    "The objective of this report is to analyze student presence trends, detect absenteeism patterns, evaluate engagement health, and offer corrective measures."
  );

  // Attendance Information
  builder.addSectionHeading("Attendance Information");
  builder.addBulletItem("Selected Batch", data.batchName || "Standard Batch");
  builder.addBulletItem("Session Date", data.sessionDate ? format(new Date(data.sessionDate), "EEEE, dd MMMM yyyy") : format(new Date(), "EEEE, dd MMMM yyyy"));
  builder.addBulletItem("Total Enrolled Roster", `${data.totalStudents} Students`);
  const presentPct = data.totalStudents > 0 ? Math.round((data.presentCount / data.totalStudents) * 100) : 0;
  const absentPct = data.totalStudents > 0 ? Math.round((data.absentCount / data.totalStudents) * 100) : 0;

  builder.addBulletItem("Present Count", `${data.presentCount} (${presentPct}%)`);
  builder.addBulletItem("Absent Count", `${data.absentCount} (${absentPct}%)`);
  if (data.lateCount !== undefined && data.lateCount > 0) {
    builder.addBulletItem("Late / Excused Count", `${data.lateCount}`);
  }
  builder.addBulletItem("Report Generated On", format(new Date(), "dd MMM yyyy"));

  // Overall Summary
  builder.addSectionHeading("Overall Summary");
  const summaryText =
    data.summary ||
    `Attendance logging for batch "${data.batchName}" on ${data.sessionDate} recorded an overall presence rate of ${data.attendancePercentage || presentPct}%. The session was conducted with high student engagement, and absent students have been flagged for automated guardian notifications.`;
  builder.addParagraph(summaryText);

  // Attendance Analysis
  builder.addSectionHeading("Attendance Analysis");
  if (data.attendanceAnalysis && data.attendanceAnalysis.length > 0) {
    data.attendanceAnalysis.forEach((item) => builder.addBulletItem(item));
  } else {
    builder.addBulletItem("Attendance %", `${data.attendancePercentage || presentPct}%`);
    builder.addBulletItem(
      "Consistency",
      data.absentCount === 0
        ? "Perfect 100% full attendance recorded for this session."
        : `Overall cohort consistency is strong, with ${data.presentCount} out of ${data.totalStudents} students attending scheduled class lectures.`
    );
    builder.addBulletItem(
      "Impact on academic performance",
      "Regular presence directly correlates with mastery in modular weekly problem sets and conceptual tests."
    );
  }

  // Students Requiring Attention
  builder.addSectionHeading("Students Requiring Attention");
  const absentees = data.studentsList?.filter((s) => s.status === "ABSENT") ?? [];
  if (absentees.length > 0) {
    absentees.forEach((stu) => {
      builder.addBulletItem(stu.name, `Marked ABSENT on ${data.sessionDate}. Follow-up recommended.`);
    });
  } else {
    builder.addParagraph("No chronic absentees or concerning attendance anomalies detected for this session.");
  }

  // Risk Indicators
  builder.addSectionHeading("Risk Indicators");
  if (data.riskIndicators && data.riskIndicators.length > 0) {
    data.riskIndicators.forEach((r) => builder.addBulletItem(r));
  } else {
    builder.addBulletItem("Cohort attendance risk level is Low with stable active enrollment.");
    builder.addBulletItem("Unexcused absence rates remain well within institutional tolerance parameters.");
  }

  // Recommendations
  builder.addSectionHeading("Recommendations");
  if (data.recommendations && data.recommendations.length > 0) {
    data.recommendations.forEach((r) => builder.addBulletItem(r));
  } else {
    builder.addBulletItem("Send automated SMS/WhatsApp alerts to guardians of unexcused absent students.");
    builder.addBulletItem("Provide lecture notes and assignment sheets to students returning from excused absence.");
    builder.addBulletItem("Reward students maintaining 100% monthly attendance with academic merit commendations.");
  }

  // Teacher Notes
  builder.addSectionHeading("Teacher Notes");
  if (data.teacherNotes && data.teacherNotes.length > 0) {
    data.teacherNotes.forEach((tn) => builder.addBulletItem(tn));
  } else {
    builder.addBulletItem("Confirm student presence at the start of each class slot.");
    builder.addBulletItem("Brief absentees on missed syllabus topics during office doubt hours.");
  }

  // Parent Guidance
  builder.addSectionHeading("Parent Guidance");
  if (data.parentGuidance && data.parentGuidance.length > 0) {
    data.parentGuidance.forEach((pg) => builder.addBulletItem(pg));
  } else {
    builder.addBulletItem("Notify institute coordinators in advance if a student requires medical or family leave.");
    builder.addBulletItem("Ensure students review daily lecture notes if a class is unavoidably missed.");
  }

  // Conclusion
  builder.addSectionHeading("Conclusion");
  const conclusionText =
    data.conclusion ||
    `The attendance record for batch ${data.batchName} on ${data.sessionDate} reflects consistent discipline and engagement. Continued adherence to attendance protocols will maximize academic achievement.`;
  builder.addParagraph(conclusionText);

  // End Notes
  builder.addEndNotes();

  const cleanBatch = (data.batchName || "Batch").replace(/[^a-zA-Z0-9_-]/g, "_");
  const cleanDate = (data.sessionDate || "Session").replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = options?.filename || `Attendance_Intelligence_Report_${cleanBatch}_${cleanDate}.pdf`;
  builder.finalizeAndSave(filename);
}
