"""add missing tables

Revision ID: d300eec8c2ef
Revises: 1631330d5b10
Create Date: 2026-07-15 13:28:58.323917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd300eec8c2ef'
down_revision: Union[str, None] = '1631330d5b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'channel', name='uq_notif_tpl')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_subject_name')
    )
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('tutor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), nullable=False),
    sa.Column('room_or_link', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classes_batch', 'classes', ['batch_id'], unique=False)
    op.create_index('idx_classes_scheduled_at', 'classes', ['tenant_id', 'scheduled_at'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('passing_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exams_batch', 'exams', ['batch_id'], unique=False)
    op.create_index('idx_exams_tenant', 'exams', ['tenant_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installments', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_ref', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nlog_recipient', 'notification_logs', ['recipient_id'], unique=False)
    op.create_index('idx_nlog_tenant', 'notification_logs', ['tenant_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_email_purpose', 'otp_verifications', ['email', 'purpose'], unique=False)
    op.create_index('idx_otp_user', 'otp_verifications', ['user_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('taken_by', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'session_date', name='uq_att_session')
    )
    op.create_index('idx_att_sess_date', 'attendance_sessions', ['tenant_id', 'session_date'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_la_lead', 'lead_activities', ['lead_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_att_record')
    )
    op.create_index('idx_att_rec_student', 'attendance_records', ['student_id'], unique=False)
    op.create_table('batch_students',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'student_id')
    )
    op.create_index('idx_bs_student', 'batch_students', ['student_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('marks_obtained', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('rank_in_batch', sa.SmallInteger(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_student')
    )
    op.create_index('idx_er_exam_rank', 'exam_results', ['exam_id', 'rank_in_batch'], unique=False)
    op.create_table('fee_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('fee_structure_id', sa.UUID(), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'invoice_no', name='uq_invoice_no')
    )
    op.create_index('idx_inv_due_status', 'fee_invoices', ['tenant_id', 'due_date', 'status'], unique=False)
    op.create_index('idx_inv_student', 'fee_invoices', ['student_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pay_invoice', 'fee_payments', ['invoice_id'], unique=False)
    # op.drop_index('idx_knowledge_chunks_embedding', table_name='knowledge_chunks', postgresql_using='hnsw')
    # op.drop_index('idx_knowledge_chunks_explanation_fts', table_name='knowledge_chunks', postgresql_using='gin')
    # op.drop_index('idx_knowledge_chunks_question_fts', table_name='knowledge_chunks', postgresql_using='gin')
    # op.drop_table('knowledge_chunks')
    # op.drop_index('idx_messages_chat', table_name='messages')
    # op.drop_table('messages')
    # op.drop_table('ai_logs')
    # op.drop_table('ai_embeddings')
    # op.drop_table('ai_generated_reports')
    # op.drop_table('ai_agent_runs')
    # op.drop_index('idx_chats_user', table_name='chats')
    # op.drop_table('chats')
    # op.drop_table('user_profiles')
    # op.drop_table('ai_feedback')
    op.add_column('admissions', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.add_column('admissions', sa.Column('admission_number', sa.String(length=50), nullable=False))
    op.add_column('admissions', sa.Column('academic_year', sa.String(length=20), nullable=False))
    op.add_column('admissions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('admissions', sa.Column('applied_course', sa.String(length=150), nullable=False))
    op.add_column('admissions', sa.Column('documents_verified', sa.Boolean(), nullable=False))
    op.add_column('admissions', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('admissions', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('admissions', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('admissions', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('admissions', sa.Column('student_name', sa.String(length=150), nullable=True))
    op.add_column('admissions', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('admissions', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('admissions', sa.Column('parent_name', sa.String(length=150), nullable=True))
    op.add_column('admissions', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.add_column('admissions', sa.Column('school_name', sa.String(length=200), nullable=True))
    op.add_column('admissions', sa.Column('grade', sa.String(length=50), nullable=True))
    op.alter_column('admissions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('admissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admissions', 'board_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('admissions', 'batch_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('admissions', 'subjects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('admissions', 'payment_installment_schedule',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('admissions', 'documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('idx_admissions_user', table_name='admissions')
    op.create_index('idx_admissions_lead', 'admissions', ['tenant_id', 'lead_id'], unique=False)
    op.create_index('idx_admissions_status', 'admissions', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_admissions_tenant', 'admissions', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_admission_number', 'admissions', ['tenant_id', 'admission_number'])
    op.drop_constraint('admissions_user_id_fkey', 'admissions', type_='foreignkey')
    op.create_foreign_key(None, 'admissions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'admissions', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'admissions', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.drop_column('admissions', 'user_id')
    op.add_column('batches', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('batches', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('batches', sa.Column('target_exam', sa.String(length=150), nullable=True))
    op.add_column('batches', sa.Column('academic_year', sa.String(length=20), nullable=False))
    op.add_column('batches', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('batches', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('batches', sa.Column('capacity', sa.SmallInteger(), nullable=False))
    op.add_column('batches', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('batches', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('batches', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('batches', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('batches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_batches_active', 'batches', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_batches_tenant', 'batches', ['tenant_id'], unique=False)
    op.drop_index('idx_gc_tenant', table_name='growth_cards')
    op.add_column('leads', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('full_name', sa.String(length=150), nullable=False))
    op.add_column('leads', sa.Column('parent_name', sa.String(length=150), nullable=True))
    op.add_column('leads', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('parent_contact_number', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('school_name', sa.String(length=150), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('leads', sa.Column('interested_course', sa.String(length=150), nullable=True))
    op.add_column('leads', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.add_column('leads', sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('board_name', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.alter_column('leads', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'subjects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('idx_leads_follow', 'leads', ['tenant_id', 'follow_up_date'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_leads_tenant', 'leads', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('leads', 'name')
    op.add_column('students', sa.Column('admission_id', sa.UUID(), nullable=False))
    op.add_column('students', sa.Column('joined_at', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('enrollment_no', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('blood_group', sa.String(length=5), nullable=True))
    op.add_column('students', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('parent_name', sa.String(length=150), nullable=True))
    op.add_column('students', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('parent_email', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('school_name', sa.String(length=200), nullable=True))
    op.add_column('students', sa.Column('current_class', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('target_exam', sa.String(length=150), nullable=True))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('left_at', sa.Date(), nullable=True))
    op.alter_column('students', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('students', 'subjects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_students_user', table_name='students')
    op.drop_constraint('students_user_id_key', 'students', type_='unique')
    op.create_index('idx_students_active', 'students', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_students_tenant', 'students', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_students_admission_id'), 'students', ['admission_id'], unique=True)
    op.create_unique_constraint('uq_enrollment', 'students', ['tenant_id', 'enrollment_no'])
    op.drop_constraint('students_batch_id_fkey', 'students', type_='foreignkey')
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    op.drop_column('students', 'batch_id')
    op.add_column('syllabus_items', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.add_column('syllabus_items', sa.Column('sort_order', sa.SmallInteger(), nullable=False))
    op.add_column('syllabus_items', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_index('idx_syllabus_items_batch', table_name='syllabus_items')
    op.drop_index('idx_syllabus_items_tenant', table_name='syllabus_items')
    op.drop_constraint('uq_syllabus_item', 'syllabus_items', type_='unique')
    op.create_index('idx_syllabus_subject', 'syllabus_items', ['subject_id'], unique=False)
    op.drop_constraint('syllabus_items_batch_id_fkey', 'syllabus_items', type_='foreignkey')
    op.create_foreign_key(None, 'syllabus_items', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'syllabus_items', 'syllabus_items', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('syllabus_items', 'batch_id')
    op.drop_column('syllabus_items', 'order')
    op.drop_column('syllabus_items', 'subject')
    op.add_column('syllabus_progress', sa.Column('topic_id', sa.UUID(), nullable=False))
    op.add_column('syllabus_progress', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('syllabus_progress', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True))
    op.drop_index('idx_syllabus_progress_item', table_name='syllabus_progress')
    op.drop_index('idx_syllabus_progress_tenant', table_name='syllabus_progress')
    op.drop_constraint('uq_syllabus_progress', 'syllabus_progress', type_='unique')
    op.create_unique_constraint('uq_syllabus_progress', 'syllabus_progress', ['batch_id', 'topic_id'])
    op.drop_constraint('syllabus_progress_item_id_fkey', 'syllabus_progress', type_='foreignkey')
    op.create_foreign_key(None, 'syllabus_progress', 'syllabus_items', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('syllabus_progress', 'completed')
    op.drop_column('syllabus_progress', 'item_id')
    op.drop_index('idx_tenants_subdomain', table_name='tenants')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index('idx_users_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_unique_constraint('uq_users_tenant_email', 'users', ['tenant_id', 'email'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('uq_users_tenant_email', 'users', type_='unique')
    op.drop_index('idx_users_role', table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_tenants_subdomain', 'tenants', ['subdomain'], unique=False)
    op.add_column('syllabus_progress', sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('syllabus_progress', sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'syllabus_progress', type_='foreignkey')
    op.create_foreign_key('syllabus_progress_item_id_fkey', 'syllabus_progress', 'syllabus_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_syllabus_progress', 'syllabus_progress', type_='unique')
    op.create_unique_constraint('uq_syllabus_progress', 'syllabus_progress', ['item_id', 'batch_id'])
    op.create_index('idx_syllabus_progress_tenant', 'syllabus_progress', ['tenant_id'], unique=False)
    op.create_index('idx_syllabus_progress_item', 'syllabus_progress', ['item_id'], unique=False)
    op.drop_column('syllabus_progress', 'updated_at')
    op.drop_column('syllabus_progress', 'status')
    op.drop_column('syllabus_progress', 'topic_id')
    op.add_column('syllabus_items', sa.Column('subject', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('syllabus_items', sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('syllabus_items', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'syllabus_items', type_='foreignkey')
    op.drop_constraint(None, 'syllabus_items', type_='foreignkey')
    op.create_foreign_key('syllabus_items_batch_id_fkey', 'syllabus_items', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_syllabus_subject', table_name='syllabus_items')
    op.create_unique_constraint('uq_syllabus_item', 'syllabus_items', ['batch_id', 'title'])
    op.create_index('idx_syllabus_items_tenant', 'syllabus_items', ['tenant_id'], unique=False)
    op.create_index('idx_syllabus_items_batch', 'syllabus_items', ['batch_id'], unique=False)
    op.drop_column('syllabus_items', 'parent_id')
    op.drop_column('syllabus_items', 'sort_order')
    op.drop_column('syllabus_items', 'subject_id')
    op.add_column('students', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('students_batch_id_fkey', 'students', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_enrollment', 'students', type_='unique')
    op.drop_index(op.f('ix_students_admission_id'), table_name='students')
    op.drop_index('idx_students_tenant', table_name='students')
    op.drop_index('idx_students_active', table_name='students')
    op.create_unique_constraint('students_user_id_key', 'students', ['user_id'])
    op.create_index('idx_students_user', 'students', ['user_id'], unique=False)
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'subjects',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('students', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('students', 'left_at')
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'target_exam')
    op.drop_column('students', 'current_class')
    op.drop_column('students', 'school_name')
    op.drop_column('students', 'parent_email')
    op.drop_column('students', 'parent_phone')
    op.drop_column('students', 'parent_name')
    op.drop_column('students', 'pincode')
    op.drop_column('students', 'state')
    op.drop_column('students', 'city')
    op.drop_column('students', 'address')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'email')
    op.drop_column('students', 'photo_url')
    op.drop_column('students', 'blood_group')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'enrollment_no')
    op.drop_column('students', 'joined_at')
    op.drop_column('students', 'admission_id')
    op.add_column('leads', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index('idx_leads_tenant', table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_follow', table_name='leads')
    op.alter_column('leads', 'subjects',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'documents',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('leads', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('leads', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('leads', 'batch_id')
    op.drop_column('leads', 'board_name')
    op.drop_column('leads', 'converted_at')
    op.drop_column('leads', 'follow_up_date')
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'grade')
    op.drop_column('leads', 'interested_course')
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'school_name')
    op.drop_column('leads', 'parent_contact_number')
    op.drop_column('leads', 'parent_phone')
    op.drop_column('leads', 'parent_name')
    op.drop_column('leads', 'full_name')
    op.drop_column('leads', 'assigned_to')
    op.create_index('idx_gc_tenant', 'growth_cards', ['tenant_id'], unique=False)
    op.drop_index('idx_batches_tenant', table_name='batches')
    op.drop_index('idx_batches_active', table_name='batches')
    op.alter_column('batches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('batches', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('batches', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('batches', 'schedule')
    op.drop_column('batches', 'is_active')
    op.drop_column('batches', 'capacity')
    op.drop_column('batches', 'end_date')
    op.drop_column('batches', 'start_date')
    op.drop_column('batches', 'academic_year')
    op.drop_column('batches', 'target_exam')
    op.drop_column('batches', 'description')
    op.drop_column('batches', 'code')
    op.add_column('admissions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.create_foreign_key('admissions_user_id_fkey', 'admissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_admission_number', 'admissions', type_='unique')
    op.drop_index('idx_admissions_tenant', table_name='admissions')
    op.drop_index('idx_admissions_status', table_name='admissions')
    op.drop_index('idx_admissions_lead', table_name='admissions')
    op.create_index('idx_admissions_user', 'admissions', ['user_id'], unique=False)
    op.alter_column('admissions', 'documents',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('admissions', 'payment_installment_schedule',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admissions', 'subjects',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('admissions', 'batch_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('admissions', 'board_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('admissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admissions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('admissions', 'grade')
    op.drop_column('admissions', 'school_name')
    op.drop_column('admissions', 'parent_phone')
    op.drop_column('admissions', 'parent_name')
    op.drop_column('admissions', 'email')
    op.drop_column('admissions', 'phone')
    op.drop_column('admissions', 'student_name')
    op.drop_column('admissions', 'approved_at')
    op.drop_column('admissions', 'updated_by')
    op.drop_column('admissions', 'approved_by')
    op.drop_column('admissions', 'remarks')
    op.drop_column('admissions', 'documents_verified')
    op.drop_column('admissions', 'applied_course')
    op.drop_column('admissions', 'status')
    op.drop_column('admissions', 'academic_year')
    op.drop_column('admissions', 'admission_number')
    op.drop_column('admissions', 'lead_id')
    op.create_table('ai_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ai_feedback_rating_check'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='ai_feedback_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_feedback_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ai_feedback_pkey')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('class_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('board', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('strengths', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('learning_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='user_profiles_user_id_key')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), server_default=sa.text("'New Conversation'::character varying"), autoincrement=False, nullable=True),
    sa.Column('chat_type', sa.VARCHAR(length=50), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chats_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_chats_user', 'chats', ['user_id'], unique=False)
    op.create_table('ai_agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('steps_executed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_agent_runs_pkey')
    )
    op.create_table('ai_generated_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='ai_generated_reports_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_generated_reports_pkey')
    )
    op.create_table('ai_embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_embeddings_pkey')
    )
    op.create_table('ai_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ai_logs_pkey')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("sender::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying]::text[])", name='messages_sender_check'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='messages_chat_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('idx_messages_chat', 'messages', ['chat_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='knowledge_chunks_pkey')
    )
    op.create_index('idx_knowledge_chunks_question_fts', 'knowledge_chunks', [sa.text("to_tsvector('english'::regconfig, question)")], unique=False, postgresql_using='gin')
    op.create_index('idx_knowledge_chunks_explanation_fts', 'knowledge_chunks', [sa.text("to_tsvector('english'::regconfig, explanation)")], unique=False, postgresql_using='gin')
    # op.create_index('idx_knowledge_chunks_embedding', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index('idx_pay_invoice', table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index('idx_inv_student', table_name='fee_invoices')
    op.drop_index('idx_inv_due_status', table_name='fee_invoices')
    op.drop_table('fee_invoices')
    op.drop_index('idx_er_exam_rank', table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index('idx_bs_student', table_name='batch_students')
    op.drop_table('batch_students')
    op.drop_index('idx_att_rec_student', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('idx_la_lead', table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index('idx_att_sess_date', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('idx_otp_user', table_name='otp_verifications')
    op.drop_index('idx_otp_email_purpose', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index('idx_nlog_tenant', table_name='notification_logs')
    op.drop_index('idx_nlog_recipient', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('fee_structures')
    op.drop_index('idx_exams_tenant', table_name='exams')
    op.drop_index('idx_exams_batch', table_name='exams')
    op.drop_table('exams')
    op.drop_index('idx_classes_scheduled_at', table_name='classes')
    op.drop_index('idx_classes_batch', table_name='classes')
    op.drop_table('classes')
    op.drop_table('subjects')
    op.drop_table('otp_codes')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
