"""sync models after base tables

Revision ID: ffb6954a2ad5
Revises: 1631330d5b10
Create Date: 2026-07-25 17:34:04.717504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffb6954a2ad5'
down_revision: Union[str, None] = '1631330d5b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syllabus_items', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.add_column('syllabus_items', sa.Column('sort_order', sa.SmallInteger(), nullable=False))
    op.add_column('syllabus_items', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_syllabus_item', 'syllabus_items', type_='unique')
    op.create_index('idx_syllabus_subject', 'syllabus_items', ['subject_id'], unique=False)
    op.drop_constraint('syllabus_items_batch_id_fkey', 'syllabus_items', type_='foreignkey')
    op.create_foreign_key(None, 'syllabus_items', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'syllabus_items', 'syllabus_items', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('syllabus_items', 'order')
    op.drop_column('syllabus_items', 'batch_id')
    op.drop_column('syllabus_items', 'subject')
    op.add_column('syllabus_progress', sa.Column('topic_id', sa.UUID(), nullable=False))
    op.add_column('syllabus_progress', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('syllabus_progress', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True))
    op.drop_constraint('uq_syllabus_progress', 'syllabus_progress', type_='unique')
    op.create_unique_constraint('uq_syllabus_progress', 'syllabus_progress', ['batch_id', 'topic_id'])
    op.create_index('idx_syllabus_progress_batch', 'syllabus_progress', ['batch_id'], unique=False)
    op.drop_constraint('syllabus_progress_item_id_fkey', 'syllabus_progress', type_='foreignkey')
    op.create_foreign_key(None, 'syllabus_progress', 'syllabus_items', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('syllabus_progress', 'completed')
    op.drop_column('syllabus_progress', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syllabus_progress', sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('syllabus_progress', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'syllabus_progress', type_='foreignkey')
    op.create_foreign_key('syllabus_progress_item_id_fkey', 'syllabus_progress', 'syllabus_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_syllabus_progress_batch', table_name='syllabus_progress')
    op.drop_constraint('uq_syllabus_progress', 'syllabus_progress', type_='unique')
    op.create_unique_constraint('uq_syllabus_progress', 'syllabus_progress', ['item_id', 'batch_id'])
    op.drop_column('syllabus_progress', 'updated_at')
    op.drop_column('syllabus_progress', 'status')
    op.drop_column('syllabus_progress', 'topic_id')
    op.add_column('syllabus_items', sa.Column('subject', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('syllabus_items', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('syllabus_items', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'syllabus_items', type_='foreignkey')
    op.drop_constraint(None, 'syllabus_items', type_='foreignkey')
    op.create_foreign_key('syllabus_items_batch_id_fkey', 'syllabus_items', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_syllabus_subject', table_name='syllabus_items')
    op.create_unique_constraint('uq_syllabus_item', 'syllabus_items', ['batch_id', 'title'])
    op.drop_column('syllabus_items', 'parent_id')
    op.drop_column('syllabus_items', 'sort_order')
    op.drop_column('syllabus_items', 'subject_id')
    # ### end Alembic commands ###
